 - name: setup prompt
   ansible.builtin.shell: set-prompt {{ tool_name }}

 - name: Download repo file
   ansible.builtin.get_url:
     url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
     dest: /etc/yum.repos.d/hashicorp.repo


